export interface InputAndLabelProps {
    id: string,
    name: string,
    type: string,
    placeholder: string,
    disabled: boolean,
    value: string,
    pattern?: string,
    title?: string,
    required?: boolean,
    containerClass?: string,
    inputClassName: string,
    labelClassName: string,
    accept?: string,
    multiple?: boolean,
    focusHandler?: (e: Event) => void,
    blurHandler?: (e: Event) => void,
    inputHandler?: (e: Event) => void,
    changeHandler?: (e: Event) => void
}